server:
  port: 8080
  servlet:
    context-path: /apm
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
    password:
